// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjb5SDRcjmsGQt3rqhb5k9cT1ikEKESSY',
    appId: '1:557391999095:web:6f1641d933b68638605672',
    messagingSenderId: '557391999095',
    projectId: 'chat-app-3efba',
    authDomain: 'chat-app-3efba.firebaseapp.com',
    storageBucket: 'chat-app-3efba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHmGg-N0crqhFropz-QlCyv7-XLKpUFDo',
    appId: '1:557391999095:android:02a4ae0d4f6c03ef605672',
    messagingSenderId: '557391999095',
    projectId: 'chat-app-3efba',
    storageBucket: 'chat-app-3efba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqLaGbzlt6LGL7gWw-nsVTglk3wwj9Rc',
    appId: '1:557391999095:ios:8a7fce78240a5d12605672',
    messagingSenderId: '557391999095',
    projectId: 'chat-app-3efba',
    storageBucket: 'chat-app-3efba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqLaGbzlt6LGL7gWw-nsVTglk3wwj9Rc',
    appId: '1:557391999095:ios:48af63dbfc3f9ae8605672',
    messagingSenderId: '557391999095',
    projectId: 'chat-app-3efba',
    storageBucket: 'chat-app-3efba.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
